In [1]:
import pandas as pd


In [2]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [5]:
df.shape

(9704, 11)

In [6]:
df["fuel_type"].nunique()

2

In [7]:
missing_columns = df.isnull().any().sum()



In [8]:
missing_columns

np.int64(4)

In [9]:
max_fuel_eff = df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max()

print (max_fuel_eff)

23.759122836520497


In [10]:
# Step 1: Median value of horsepower
median_before = df["horsepower"].median()
print("Median before filling:", median_before)


Median before filling: 149.0


In [11]:
# Step 2: Most frequent value (mode)
most_frequent = df["horsepower"].mode()[0]
print("Most frequent value:", most_frequent)

Most frequent value: 152.0


In [12]:
# Step 3: Fill missing values with the most frequent value
df["horsepower"] = df["horsepower"].fillna(most_frequent)

In [13]:
# Step 4: Median after filling
median_after = df["horsepower"].median()
print("Median after filling:", median_after)

Median after filling: 152.0


In [14]:
# Step 5: Compare
if median_after > median_before:
    print("Yes, it increased")
elif median_after < median_before:
    print("Yes, it decreased")
else:
    print("No")

Yes, it increased


In [15]:
import numpy as np


In [16]:
# 1. Select all cars from Asia
asia_cars = df[df["origin"] == "Asia"]
print (asia_cars)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front

In [17]:
# 2. Select only columns vehicle_weight and model_year
X = asia_cars[["vehicle_weight", "model_year"]]
print(X)

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]


In [18]:
# 3. Select the first 7 values
X = X.head(7)
print (X)

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019


In [19]:
# 4. Get the underlying NumPy array
X = X.values   # now X is a NumPy array
X


array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [20]:
# 5. Compute XTX = X.T @ X
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [21]:
# 6. Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [22]:
# 7. Create y array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [23]:
# 8. Multiply (XTX_inv @ X.T) @ y
w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [24]:
# 9. Sum of elements in w
result = w.sum()
print("Sum of weights:", result)

Sum of weights: 0.5187709081074016
